Add more info for checks.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,15 +30,13 @@ jobs:
               uses: gradle/wrapper-validation-action@v1
 
             - name: Check style
-              run: ./gradlew lintKotlin
+              run: ./gradlew lintKotlin || echo "\n** Run './gradlew formatKotlin' to fix the style errors. **\n"
 
             - name: Check lint
               run: ./gradlew lint
 
-            # Check if there has been a binary incompatible change to the API.
-            # If this change is intentional, run `./gradlew apiDump` and commit the new API files.
             - name: Check binary compatibility
-              run: ./gradlew apiCheck
+              run: ./gradlew apiCheck || echo "\n** This PR changes Coil's public API. If this change is intentional, run './gradlew apiDump' and commit the new API files. **\n"
 
     unit-tests:
         name: Unit tests
